Homepage not logged in
GaronSmith/marvelous-movies pull request #37
Opened 2021-01-07 22:57 UTC by nicole-loescher

Here is the completed home page for a user that is not logged in. It also has the functionality to allow the user to click on the top films in a genre as well as a random movie generator.

2021-01-07 23:53 UTC, genagain requested changes
Looks pretty good! Once you address the changes I requested and/or answer my questions I'll approve it.

2021-01-07 23:53 UTC, genagain commented on public/stylesheets/index.css
> +
Please remove this extra line

2021-01-07 23:53 UTC, genagain commented on routes/index.js
> +  };
Nice! Please define this function above the router handler.

2021-01-07 23:53 UTC, genagain commented on routes/index.js
> +  const randomBest = randomNum(880);
Do you know that there will always be 880 movies in the database? If there are ever any fewer then the app would try to query a primary key that doesn't exist

2021-01-07 23:53 UTC, genagain commented on views/index.pug
> +          a(href='/movies/genre/Action') Best Action
Could you pass all of the genres to the `index.pug` template an iterating over them to render these links?

2021-01-08 00:58 UTC, nicole-loescher commented
Hey Gen, thank you for taking a look. Those requested changes have been made!

2021-01-08 01:42 UTC, genagain approved these changes
Looks good to me! Ship it! 🚀

2021-01-08 16:34 UTC, merged